### ISSUE TITLE
Add farmOS Link

### ISSUE THREAD

**Issue by w0244079** [NSCC-Blackbird2023/GitKit-FarmData2#30]
Change the word "farmOS" into a link in the Acknowledgements at the bottom of README.md.  

The URL to use for the link is: https://farmos.org/

The "Links" section of the following document shows how to create a link using Markdown:
- https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

**Comment by Yashshah1902** [comment]
I would like to work on this issue!

**Comment by PatMcco** [comment]
yoink

**Comment by MatheusChampion** [comment]
working on it

**Comment by kcolter** [comment]
working on this issue

**Comment by Teixeira-Gabriel** [comment]
working on it

**Comment by naeimrahimi** [comment]
working on it

**Comment by flx-dev** [comment]
working on this issue
